global using LXIntegratedNavigation.WPF.ViewModels;
global using LXIntegratedNavigation.WPF.Views;
global using UtcTime = System.DateTimeOffset;
global using static LXIntegratedNavigation.WPF.App;
global using Orientation = NaviSharp.Orientation;
global using Vector = NaviSharp.Vector<double>;
global using NavigationService = LXIntegratedNavigation.WPF.Services.NavigationService;
global using System.Windows;
global using static NaviSharp.Angle;
global using static LXIntegratedNavigation.Shared.Helpers.FileHelper;
global using Wpf.Ui.Common;
global using Microsoft.Extensions.DependencyInjection;